apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "quantumleap.fullname" . }}
  labels:
    {{- include "quantumleap.labels" . | nindent 4 }}
data:
  config.yml: |
    {{- toYaml .Values.config | trim | nindent 4 }}
