{{- if eq .Values.quantumleap.defaultdb "timescale" -}}

{{- $pgPassword := default (randAlphaNum 12) .Values.database.timescale.dbpass | b64enc | quote }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-timescale
  labels:
    {{- include "quantumleap.labels" . | nindent 4 }}
type: Opaque
data:
  POSTGRES_DB_PASS: {{ $pgPassword }}
{{- end }}